<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Modelización | Análisis de Series de Tiempo relacionados con COVID19</title>
  <meta name="description" content="Se incluye un análisis de series de tiempo con datos relacionados con el COVID 19 desde 2020 hasta enero de 2024" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Modelización | Análisis de Series de Tiempo relacionados con COVID19" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Se incluye un análisis de series de tiempo con datos relacionados con el COVID 19 desde 2020 hasta enero de 2024" />
  <meta name="github-repo" content="Familia GSMSciencede tiempo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Modelización | Análisis de Series de Tiempo relacionados con COVID19" />
  
  <meta name="twitter:description" content="Se incluye un análisis de series de tiempo con datos relacionados con el COVID 19 desde 2020 hasta enero de 2024" />
  

<meta name="author" content="GRUPO 6: Maria José Reina Torres, Sonia Yurany Gallego Paz, Juan José León Tabares" />


<meta name="date" content="2024-05-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="descomposición-de-la-serie-de-tiempo..html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="introducción.html"><a href="introducción.html"><i class="fa fa-check"></i><b>1</b> Introducción:</a></li>
<li class="chapter" data-level="2" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html"><i class="fa fa-check"></i><b>2</b> Análisis Exploratorio de datos:</a>
<ul>
<li class="chapter" data-level="2.1" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#exploración-y-preprocesamiento-del-dataset"><i class="fa fa-check"></i><b>2.1</b> Exploración y preprocesamiento del dataset:</a></li>
<li class="chapter" data-level="2.2" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#estructura-y-exploración-de-datos-en-serie-de-tiempo"><i class="fa fa-check"></i><b>2.2</b> Estructura y exploración de datos en serie de tiempo:</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="descomposición-de-la-serie-de-tiempo..html"><a href="descomposición-de-la-serie-de-tiempo..html"><i class="fa fa-check"></i><b>3</b> Descomposición de la serie de tiempo.</a></li>
<li class="chapter" data-level="4" data-path="modelización.html"><a href="modelización.html"><i class="fa fa-check"></i><b>4</b> Modelización</a>
<ul>
<li class="chapter" data-level="4.1" data-path="modelización.html"><a href="modelización.html#método-de-holt-winter"><i class="fa fa-check"></i><b>4.1</b> Método de Holt-Winter:</a></li>
<li class="chapter" data-level="4.2" data-path="modelización.html"><a href="modelización.html#método-de-suavizamiento-exponencial"><i class="fa fa-check"></i><b>4.2</b> Método de Suavizamiento Exponencial:</a></li>
<li class="chapter" data-level="4.3" data-path="modelización.html"><a href="modelización.html#modelos-estacionarios-en-series-de-tiempo-metodología-box-jenkins"><i class="fa fa-check"></i><b>4.3</b> Modelos estacionarios en series de tiempo: Metodología Box-Jenkins</a></li>
<li class="chapter" data-level="4.4" data-path="modelización.html"><a href="modelización.html#algoritmo-facebooks-prophet"><i class="fa fa-check"></i><b>4.4</b> Algoritmo Facebook´s Prophet</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis de Series de Tiempo relacionados con COVID19</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelización" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Modelización<a href="modelización.html#modelización" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="método-de-holt-winter" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Método de Holt-Winter:<a href="modelización.html#método-de-holt-winter" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El suavizado exponencial de Holt-Winter es una de las técnicas de análisis de series de tiempo más antiguas que tiene en cuenta la tendencia y la estacionalidad al hacer el pronóstico. Este método tiene 3 aspectos principales para realizar las predicciones que son tres tipos de suavizado exponencial. Tiene un valor medio con la tendencia y la estacionalidad.</p>
<p><strong>Descripción ampliada de los datos:</strong></p>
<p>Iniciamos graficando nuevamente el índice de los casos nuevos de Covid a través del tiempo</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="modelización.html#cb54-1" tabindex="-1"></a><span class="fu">plot</span>((indice_casos.ts),<span class="at">ylab=</span><span class="st">&quot;(indice_casos)&quot;</span>,<span class="at">xlab=</span><span class="st">&#39;Año&#39;</span>, <span class="at">main =</span><span class="st">&#39;Casos nuevos de Covid&#39;</span>)</span>
<span id="cb54-2"><a href="modelización.html#cb54-2" tabindex="-1"></a></span>
<span id="cb54-3"><a href="modelización.html#cb54-3" tabindex="-1"></a>time_indices <span class="ot">&lt;-</span> <span class="fu">time</span>(indice_casos.ts)</span>
<span id="cb54-4"><a href="modelización.html#cb54-4" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(indice_casos.ts <span class="sc">~</span> time_indices)</span>
<span id="cb54-5"><a href="modelización.html#cb54-5" tabindex="-1"></a><span class="fu">abline</span>(modelo, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>En la gráfica anterior se observa la tendencia y el comportamiento de los casos nuevos de covid.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="modelización.html#cb55-1" tabindex="-1"></a><span class="fu">cycle</span>(indice_casos.ts)</span></code></pre></div>
<pre><code>##      Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
## 2020   1   2   3   4   5   6   7   8   9  10  11  12
## 2021   1   2   3   4   5   6   7   8   9  10  11  12
## 2022   1   2   3   4   5   6   7   8   9  10  11  12
## 2023   1   2   3   4   5   6   7   8   9  10  11  12
## 2024   1   2   3</code></pre>
<p>Con la función cycle se identifica el ciclo al que pertenece cada dato en la serie temporal, en nuestro caso, tenemos datos agrupados por mes con una frecuencia de 12, esta función asigna un número del 1 al 12 a cada mes. Posteriormente calculamos una medida resumen para cada periodo, en este caso un promedio mensual.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="modelización.html#cb57-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">aggregate</span>(indice_casos.ts, <span class="at">FUN =</span> mean))</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>Se observa claramente los meses pico con tendencia más alta, en la gráfica es a inicio del 2022.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="modelización.html#cb58-1" tabindex="-1"></a><span class="fu">boxplot</span>(indice_casos.ts<span class="sc">~</span><span class="fu">cycle</span>(indice_casos.ts))</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>En la gráfica anterior, cada caja indica la variabilidad de los casos nuevos dentro de cada mes, las cajas más anchas indican mayor variabilidad en el mes como en los meses de enero y diciembre.</p>
<p>Se observa la mediana de casos nuevos de covid de forma mensual, con una mediana mayor en los meses de mayor variabilidad y agosto. La menor se encuentra en febrero y marzo, siendo ambos meses los que tienen datos outlier.</p>
<p>A través de la función logaritmo que se aplica a continuación, se busca visualizar mejor los datos de casos nuevos de covid:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="modelización.html#cb59-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(indice_casos.ts),<span class="at">ylab=</span><span class="st">&quot;log(Casos nuevos)&quot;</span>,<span class="at">xlab=</span><span class="st">&#39;Año&#39;</span>, <span class="at">main =</span><span class="st">&#39;Logaritmo de casos nuevos de Covid&#39;</span>)</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>Como se puede ver en la gráfica anterior, se evidencia una transformación de los datos, destacando una reducción en la variabilidad y una mayor estabilidad a lo largo del tiempo. Entre el año 2020 y 2021 la tendencia es creciente en número de casos, parece más estable con algunas variaciones entre el año 2021 y 2023, a partir de ahí, se observa decreciente.</p>
<p><strong>Aplicación del modelo Holt-Winter:</strong></p>
<p>Teniendo en cuenta la transformación anterior, procedemos a aplicar el modelo de Holt - Winter utilizando la manera aditiva:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="modelización.html#cb60-1" tabindex="-1"></a>modelo_HW <span class="ot">=</span> <span class="fu">HoltWinters</span>(<span class="fu">log</span>(indice_casos.ts), <span class="at">seasonal=</span><span class="st">&quot;additive&quot;</span>)</span>
<span id="cb60-2"><a href="modelización.html#cb60-2" tabindex="-1"></a><span class="fu">plot</span>(modelo_HW, <span class="at">main=</span><span class="st">&quot;Ajuste con Holt-Winters&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Año&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;log(Casos nuevos)&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>Con la aplicación de este método, se crea una línea de color rojo con una nueva serie de datos, en la cual se puede observar una proximidad entre los puntos con los datos originales color negro. Al aplicar el método de Holt-Winter para ajustar los datos, se nota que este método es adecuado, ya que sigue de buena forma el comportamiento de los datos, con una leve variación en el año 2022, sin embargo, se observa un buen ajuste.</p>
<p>A continuación, se descompone la serie de acuerdo a las características:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="modelización.html#cb61-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(modelo_HW), <span class="at">main=</span><span class="st">&quot;Descomposición con HW&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Año&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;log(Casos nuevos)&quot;</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>Se puede evidenciar en la gráfica, que con las transformaciones realizadas se reduce el Random, lo que puede ayudar a generar una buena predicción.</p>
<p>Xhat grafica los valores ajustados, representa la estimación ajustada de la serie temporal basándose en el modelo Holt-Winters. Muestra cómo el modelo captura la tendencia y la estacionalidad.</p>
<p>El level o nivel indica el nivel subyacente de la serie de nuevos casos de covid en cada punto del tiempo. Es una estimación suave del promedio de la serie en el tiempo. Refleja una tendencia al final descendente.</p>
<p>El trend o tendencia refleja el componente de tendencia de la serie temporal. Es la velocidad a la que el nivel está cambiando con el tiempo. La tendencia observada es decreciente.</p>
<p>La gráfica de Season o estacionalidad muestra si hay patrones cíclicos, lo cual no es evidente en este caso. Cada valor estacional se calcula respecto al promedio general (nivel).</p>
<p><strong>Predicción:</strong></p>
<p>Ahora, se realizará la predicción para el año siguiente (12 meses) de los casos nuevos de Covid</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="modelización.html#cb62-1" tabindex="-1"></a>pred<span class="ot">=</span><span class="fu">predict</span>(modelo_HW, <span class="dv">12</span>, <span class="at">prediction.interval =</span> <span class="cn">TRUE</span>)</span>
<span id="cb62-2"><a href="modelización.html#cb62-2" tabindex="-1"></a>pred</span></code></pre></div>
<pre><code>##               fit      upr       lwr
## Apr 2024 13.96551 15.21492 12.716107
## May 2024 13.74096 15.28488 12.197045
## Jun 2024 13.30177 15.13670 11.466830
## Jul 2024 13.85985 15.98712 11.732574
## Aug 2024 14.03887 16.46227 11.615464
## Sep 2024 13.49625 16.22097 10.771525
## Oct 2024 13.41748 16.44952 10.385444
## Nov 2024 13.35777 16.70361 10.011922
## Dec 2024 14.01899 17.68542 10.352567
## Jan 2025 13.60447 17.59842  9.610529
## Feb 2025 12.57885 16.90733  8.250369
## Mar 2025 12.34571 17.01576  7.675656</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="modelización.html#cb64-1" tabindex="-1"></a><span class="fu">plot</span>(modelo_HW,pred)</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>De esta forma se puede observar la tendencia del comportamiento para los próximos 12 meses, con sus respectivos intervalos de confianza, la cual se presenta en descenso.</p>
</div>
<div id="método-de-suavizamiento-exponencial" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Método de Suavizamiento Exponencial:<a href="modelización.html#método-de-suavizamiento-exponencial" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El suavizamiento exponencial es un tipo de promedio ponderado que estima el valor futuro en función del pronóstico anterior más un porcentaje de error pronosticado.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="modelización.html#cb65-1" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb65-2"><a href="modelización.html#cb65-2" tabindex="-1"></a>fit_ses<span class="ot">&lt;-</span><span class="fu">ses</span>(<span class="fu">log</span>(indice_casos.ts),<span class="at">h=</span><span class="dv">1</span>, <span class="at">initial=</span><span class="st">&quot;simple&quot;</span>,<span class="at">alpha=</span><span class="fl">0.1</span>)</span>
<span id="cb65-3"><a href="modelización.html#cb65-3" tabindex="-1"></a>fit_ses</span></code></pre></div>
<pre><code>##          Point Forecast    Lo 80   Hi 80    Lo 95    Hi 95
## Apr 2024       15.84566 12.24843 19.4429 10.34417 21.34716</code></pre>
<p>El pronóstico es de 15.84 con los intervalos de predicción Lo(bajo) y Hi (Alto)</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="modelización.html#cb67-1" tabindex="-1"></a><span class="fu">summary</span>(fit_ses)</span></code></pre></div>
<pre><code>## 
## Forecast method: Simple exponential smoothing
## 
## Model Information:
## Simple exponential smoothing 
## 
## Call:
##  ses(y = log(indice_casos.ts), h = 1, initial = &quot;simple&quot;, alpha = 0.1) 
## 
##   Smoothing parameters:
##     alpha = 0.1 
## 
##   Initial states:
##     l = 9.0045 
## 
##   sigma:  2.8069
## Error measures:
##                    ME     RMSE      MAE      MPE     MAPE     MASE      ACF1
## Training set 1.341396 2.806937 2.274939 7.479261 13.56641 1.192265 0.9192371
## 
## Forecasts:
##          Point Forecast    Lo 80   Hi 80    Lo 95    Hi 95
## Apr 2024       15.84566 12.24843 19.4429 10.34417 21.34716</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="modelización.html#cb69-1" tabindex="-1"></a><span class="fu">plot</span>(fit_ses)</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>El valor pronosticado para abril de 2024 sería de 15.8 casos nuevos de covid con un intervalo 95% entre 10 y 21 casos. en general, con el suavizado, se mantiene la tendencia a la disminución en el número de casos nuevos.</p>
</div>
<div id="modelos-estacionarios-en-series-de-tiempo-metodología-box-jenkins" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Modelos estacionarios en series de tiempo: Metodología Box-Jenkins<a href="modelización.html#modelos-estacionarios-en-series-de-tiempo-metodología-box-jenkins" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Se aplica a los modelos autorregresivos de media móvil ARMA o a los modelos autorregresivos integrados de media móvil ARIMA para encontrar el mejor ajuste de una serie temporal con el fin de que los pronósticos sean más acertados.</p>
<p>Dentro de los pasos a seguir, tenemos:</p>
<ul>
<li>Visualizar la serie.</li>
<li>Transformarla en estacionaria.</li>
<li>Graficar ACF - PACF, escoger los parámetros.</li>
<li>Construir el modelo.</li>
<li>Hacer predicción.</li>
</ul>
<p><strong>Visualizar la Serie y transformarla en estacionaria:</strong></p>
<p>Como se expuso en el punto 3. de este documento, el valor p de la prueba de Dickey-Fuller aumentado (ADF)es 0.4587, indica que no hay suficiente evidencia para rechazar la hipótesis nula de que la serie no es estacionaria, en estos casos, se requeriría transformar o diferenciar los datos para que sean estacionarios.</p>
<p>En ese caso, se aplicó una primera diferenciación en la variable covid_ts_diff dónde se obtuvo un valor p menor de 0.01, indica que ya es posible rechazar la hipótesis nula y concluir que la serie es estacionaria después de la primera diferenciación.</p>
<p><strong>Graficar ACF - PACF, escoger los parámetros:</strong></p>
<p>Se realiza gráfico de las Funciones de autocovarianza (ACF) y autocorrelación (PACF):</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="modelización.html#cb70-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb70-2"><a href="modelización.html#cb70-2" tabindex="-1"></a>ACF_dif1<span class="ot">&lt;-</span><span class="fu">acf</span>(covid_ts_diff)</span>
<span id="cb70-3"><a href="modelización.html#cb70-3" tabindex="-1"></a>PACF_dif1<span class="ot">&lt;-</span><span class="fu">pacf</span>(covid_ts_diff)</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>La descripción de estas gráficas ya fue realizada.</p>
<p><strong>Construir el modelo y hacer predicción:</strong></p>
<p>Teniendo en cuenta esto, se procede a aplicar el modelo sugerido ARIMA:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="modelización.html#cb71-1" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb71-2"><a href="modelización.html#cb71-2" tabindex="-1"></a></span>
<span id="cb71-3"><a href="modelización.html#cb71-3" tabindex="-1"></a>modelo_dif1<span class="ot">&lt;-</span><span class="fu">auto.arima</span>(covid_ts_diff)</span>
<span id="cb71-4"><a href="modelización.html#cb71-4" tabindex="-1"></a>modelo_dif1</span></code></pre></div>
<pre><code>## Series: covid_ts_diff 
## ARIMA(0,0,2) with zero mean 
## 
## Coefficients:
##           ma1      ma2
##       -0.3486  -0.3198
## s.e.   0.1298   0.1252
## 
## sigma^2 = 4381003968820263:  log likelihood = -970.59
## AIC=1947.18   AICc=1947.7   BIC=1952.91</code></pre>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="modelización.html#cb73-1" tabindex="-1"></a>pronostico_dif1<span class="ot">&lt;-</span> <span class="fu">forecast</span>(modelo_dif1,<span class="dv">12</span>,<span class="at">level=</span><span class="dv">95</span>)</span>
<span id="cb73-2"><a href="modelización.html#cb73-2" tabindex="-1"></a>pronostico_dif1</span></code></pre></div>
<pre><code>##          Point Forecast      Lo 95     Hi 95
## Apr 2024        3473922 -126254434 133202278
## May 2024        1533567 -135851075 138918209
## Jun 2024              0 -143510950 143510950
## Jul 2024              0 -143510950 143510950
## Aug 2024              0 -143510950 143510950
## Sep 2024              0 -143510950 143510950
## Oct 2024              0 -143510950 143510950
## Nov 2024              0 -143510950 143510950
## Dec 2024              0 -143510950 143510950
## Jan 2025              0 -143510950 143510950
## Feb 2025              0 -143510950 143510950
## Mar 2025              0 -143510950 143510950</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="modelización.html#cb75-1" tabindex="-1"></a><span class="fu">plot</span>(pronostico_dif1,<span class="at">main=</span><span class="st">&quot;Pronóstico con Arima para Casos nuevos de Covid con diferenciación&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Año&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;covid_ts_diff&quot;</span>)</span>
<span id="cb75-2"><a href="modelización.html#cb75-2" tabindex="-1"></a><span class="fu">grid</span>()</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<p>En resumen, el modelo ARIMA(0,0,2) con media cero refleja coeficientes significativos para los términos de media móvil, pero la alta varianza de los residuos y los valores altos de AIC, AICc y BIC indican que el modelo puede no ser óptimo y puede necesitar una revisión o ajuste adicional.</p>
<p>Además como se evidencia en la gráfica, si el pronóstico es el mismo para todos los meses, eso indica que hay un problema con el modelo ajustado.</p>
<p>Por lo anterior, se tomará la variable covid_ts_diff2 en dónde se procedió a realizar una segunda diferenciación para ver si se ajusta el modelo, antes de eso, nuevamente se procede a graficar las Funciones de autocovarianza (ACF) y autocorrelación (PACF) para estos datos:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="modelización.html#cb76-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb76-2"><a href="modelización.html#cb76-2" tabindex="-1"></a></span>
<span id="cb76-3"><a href="modelización.html#cb76-3" tabindex="-1"></a>ACF_dif2<span class="ot">&lt;-</span><span class="fu">acf</span>(covid_ts_diff2)</span>
<span id="cb76-4"><a href="modelización.html#cb76-4" tabindex="-1"></a>PACF_dif2<span class="ot">&lt;-</span><span class="fu">pacf</span>(covid_ts_diff2)</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="modelización.html#cb77-1" tabindex="-1"></a>modelo_dif2<span class="ot">&lt;-</span><span class="fu">auto.arima</span>(covid_ts_diff2)</span>
<span id="cb77-2"><a href="modelización.html#cb77-2" tabindex="-1"></a>modelo_dif2</span></code></pre></div>
<pre><code>## Series: covid_ts_diff2 
## ARIMA(5,0,1) with zero mean 
## 
## Coefficients:
##           ar1      ar2      ar3     ar4      ar5      ma1
##       -0.2801  -0.3152  -0.2428  -0.222  -0.0264  -0.9891
## s.e.   0.1509   0.1517   0.1529   0.147   0.1432   0.2526
## 
## sigma^2 = 4902090394961761:  log likelihood = -954.1
## AIC=1922.21   AICc=1924.94   BIC=1935.45</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="modelización.html#cb79-1" tabindex="-1"></a>pronostico_dif2<span class="ot">&lt;-</span> <span class="fu">forecast</span>(modelo_dif2,<span class="dv">12</span>,<span class="at">level=</span><span class="dv">95</span>)</span>
<span id="cb79-2"><a href="modelización.html#cb79-2" tabindex="-1"></a>pronostico_dif2</span></code></pre></div>
<pre><code>##          Point Forecast      Lo 95     Hi 95
## Apr 2024      265646.00 -137769977 138301269
## May 2024      450447.19 -221313463 222214357
## Jun 2024     -991831.27 -222813171 220829508
## Jul 2024     -303245.86 -223003659 222397167
## Aug 2024      194198.13 -222548543 222936939
## Sep 2024      174969.01 -224103564 224453502
## Oct 2024      171693.49 -224332235 224675622
## Nov 2024      -56898.40 -224831141 224717344
## Dec 2024     -115769.83 -224895620 224664080
## Jan 2025      -35286.01 -224815532 224744960
## Feb 2025       17456.74 -224809812 224844726
## Mar 2025       42439.07 -224791062 224875940</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="modelización.html#cb81-1" tabindex="-1"></a><span class="fu">plot</span>(pronostico_dif2,<span class="at">main=</span><span class="st">&quot;Pronóstico con Arima para Casos nuevos de Covid con segunda diferenciación&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Año&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;covid_ts_diff2&quot;</span>)</span>
<span id="cb81-2"><a href="modelización.html#cb81-2" tabindex="-1"></a><span class="fu">grid</span>()</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>Este modelo ARIMA indica que se utilizan cinco términos autorregresivos (AR) y un término de media móvil (MA), sin aplicar diferenciación (I), y el modelo no incluye un término constante distinto de cero. En resumen, el modelo ARIMA(5,0,1) parece capturar bien la estructura de la serie temporal “covid_ts_diff2”, con coeficientes significativos para los términos AR y MA. Sin embargo, siempre es importante validar el modelo y considerar si hay margen para mejorar el ajuste.</p>
<p>Ademas el pronóstico demostrado en la gráfica presenta valores muy pequeños para todos los meses.</p>
<p>Por lo anterior, se procede a aplicar logaritmo a la serie inicial para ajustar la estacionariedad y para poder mejorar el pronóstico, al igual que en los dos casos anteriores, se realiza primero el gráfico de las Funciones de autocovarianza (ACF) y autocorrelación (PACF):</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="modelización.html#cb82-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb82-2"><a href="modelización.html#cb82-2" tabindex="-1"></a>ACF_log<span class="ot">&lt;-</span><span class="fu">acf</span>(<span class="fu">log</span>(indice_casos.ts))</span>
<span id="cb82-3"><a href="modelización.html#cb82-3" tabindex="-1"></a>PACF_log<span class="ot">&lt;-</span><span class="fu">pacf</span>(<span class="fu">log</span>(indice_casos.ts))</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<p>Se continua con el cálculo:</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="modelización.html#cb83-1" tabindex="-1"></a>modelo_log<span class="ot">&lt;-</span><span class="fu">auto.arima</span>(<span class="fu">log</span>(indice_casos.ts))</span>
<span id="cb83-2"><a href="modelización.html#cb83-2" tabindex="-1"></a>modelo_log</span></code></pre></div>
<pre><code>## Series: log(indice_casos.ts) 
## ARIMA(0,2,1) 
## 
## Coefficients:
##           ma1
##       -0.6825
## s.e.   0.1537
## 
## sigma^2 = 0.692:  log likelihood = -60.32
## AIC=124.63   AICc=124.89   BIC=128.42</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="modelización.html#cb85-1" tabindex="-1"></a>pronostico_log<span class="ot">&lt;-</span> <span class="fu">forecast</span>(modelo_log,<span class="dv">12</span>,<span class="at">level=</span><span class="dv">95</span>)</span>
<span id="cb85-2"><a href="modelización.html#cb85-2" tabindex="-1"></a>pronostico_log</span></code></pre></div>
<pre><code>##          Point Forecast      Lo 95    Hi 95
## Apr 2024       13.91272 12.2822872 15.54315
## May 2024       13.67222 10.9754127 16.36902
## Jun 2024       13.43172  9.6397013 17.22373
## Jul 2024       13.19122  8.2400339 18.14240
## Aug 2024       12.95072  6.7690286 19.13241
## Sep 2024       12.71022  5.2260618 20.19438
## Oct 2024       12.46972  3.6126204 21.32682
## Nov 2024       12.22922  1.9308656 22.52758
## Dec 2024       11.98872  0.1831147 23.79433
## Jan 2025       11.74822 -1.6283594 25.12480
## Feb 2025       11.50772 -3.5014043 26.51685
## Mar 2025       11.26722 -5.4340117 27.96846</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="modelización.html#cb87-1" tabindex="-1"></a><span class="fu">plot</span>(pronostico_log,<span class="at">main=</span><span class="st">&quot;Pronóstico con Arima para Casos nuevos de Covid con transformación Log&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Año&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Log_indice_Casos&quot;</span>)</span>
<span id="cb87-2"><a href="modelización.html#cb87-2" tabindex="-1"></a><span class="fu">grid</span>()</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<p>De acuerdo con los resultados, se puede evidenciar que este modelo ARIMA indica que se utiliza un término de media móvil (MA) de orden 1 (q=1), sin términos autorregresivos (AR) (p=0), y se ha aplicado una diferenciación de segundo orden (d=2) a la serie temporal original.</p>
<p>El modelo ARIMA (0,2,1) ajustado a la serie con transformación log, proporciona una aproximación adecuada, con un solo término de media móvil y una diferenciación de segundo orden. Al aplicar esta transformación se obtiene un pronóstico más acertado, el cual también refleja una tendencia de disminución en los próximos 12 meses, lo que concuerda con la realidad observada en los nuevos casos de Covid. Por lo tanto, este pronóstico puede ser considerado como acertado para esta serie temporal.</p>
<p>Teniendo en cuenta lo anterior, se procede a calcular y graficar los residuales:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="modelización.html#cb88-1" tabindex="-1"></a>residuales<span class="ot">&lt;-</span>modelo_log<span class="sc">$</span>residuals</span>
<span id="cb88-2"><a href="modelización.html#cb88-2" tabindex="-1"></a>residuales</span></code></pre></div>
<pre><code>##               Jan          Feb          Mar          Apr          May
## 2020  0.004026955 -0.003973338 -1.172869131 -1.618126602 -1.714506050
## 2021 -0.032750553 -0.958691330  0.201545740  0.366894031  0.020677895
## 2022  1.490751161 -1.020678795 -0.498599225 -0.594446133 -0.272419992
## 2023 -0.788807669 -2.437727444  0.304434050  0.468206023 -0.310354897
## 2024 -1.093113677 -0.459642799  0.354185813                          
##               Jun          Jul          Aug          Sep          Oct
## 2020 -1.307291818 -0.654882360 -0.445398887 -0.847633672 -0.206573702
## 2021 -0.950877561  0.375597198  0.535475927 -0.505885747  0.013879699
## 2022 -0.019412721  0.989042551 -0.522673348 -0.411204652  0.304017292
## 2023 -0.281681198  0.700648947  0.620107886 -0.426759772  0.158337702
## 2024                                                                 
##               Nov          Dec
## 2020  0.272167997 -0.635556975
## 2021  0.028526950  0.294499517
## 2022 -0.312781418  1.988284537
## 2023  0.185991119  0.854329817
## 2024</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="modelización.html#cb90-1" tabindex="-1"></a><span class="fu">qqnorm</span>(residuales)</span>
<span id="cb90-2"><a href="modelización.html#cb90-2" tabindex="-1"></a><span class="fu">qqline</span>(residuales)</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>Los residuales representan la diferencia entre los valores observados y los valores predichos por el modelo. En este contexto, los residuales son las discrepancias entre los valores reales y los valores pronosticados para cada mes de los años 2020 a 2023.</p>
<p>Ahora aplicaremos el Test Shapiro con el fin de validar si los residuales presentan una distribución normal:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="modelización.html#cb91-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(residuales)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuales
## W = 0.98325, p-value = 0.6831</code></pre>
<p>Se puede evidenciar que el valor W =0.98 es cercano a 1, lo que significa que los residuales no se desvían significativamente de una distribución normal, ya que cuanto más cercano esté a 1, más consistentes son los datos con una distribución normal.</p>
<p>Por otro lado con el valor p se puede observar si los datos provienen de una población con una distribución normal. Un valor p alto (generalmente mayor que 0.05) indica que no hay suficiente evidencia para rechazar la hipótesis nula de que los datos provienen de una distribución normal. En este caso, el valor p es 0.6831, lo que sugiere que los datos tienen una distribución normal, .</p>
<p>Teniendo en cuenta lo anterior, se puede determinar que el modelo ARIMA ajustado es adecuado para los datos.</p>
<p>Finalmente aplicamos el Box-Ljung test para verificar la presencia de autocorrelación en los residuos del modelo:</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="modelización.html#cb93-1" tabindex="-1"></a><span class="fu">Box.test</span>(residuales,<span class="at">type =</span> <span class="st">&quot;Ljung-Box&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Box-Ljung test
## 
## data:  residuales
## X-squared = 0.77733, df = 1, p-value = 0.378</code></pre>
<p>El resultado del test de Box-Ljung X-squared = 0.77733 y p = 0.378 indican que no hay suficiente evidencia para afirmar que exista autocorrelación significativa en los residuales del modelo de series temporales. Por lo tanto, no se puede afirmar que haya autocorrelación en los residuales generando un impacto positivo en el modelo:</p>
<ul>
<li><p>Las predicciones del modelo no están sistemáticamente sesgadas por patrones no modelados,</p></li>
<li><p>Hay independencia de los errores reforzando la confianza en los resultados,</p></li>
<li><p>Los intervalos de confianza y las pruebas de hipótesis derivadas del modelo son más confiables</p></li>
<li><p>Los estimadores de los coeficientes del modelo son eficientes y tienen varianza mínima dando precisión a las estimaciones, y</p></li>
<li><p>Los errores en una observación no son predictivos de los errores en las observaciones futuras.</p></li>
</ul>
</div>
<div id="algoritmo-facebooks-prophet" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Algoritmo Facebook´s Prophet<a href="modelización.html#algoritmo-facebooks-prophet" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El modelo Prophet fue propuesto originalmente para pronosticar datos diarios con estacionalidad semanal y anual, además de efectos de vacaciones. Posteriormente se amplió para cubrir más tipos de datos estacionales.</p>
<p>A continuación, se aplica el algoritmo de Facebook`s Prophet al data set definido anteriormente como indice_casos.ts con la segunda diferenciación antes de iniciar con el proceso dado que ya se aplicaron las pruebas (prueba ADF) y los datos son estacionarios.</p>
<p>De acuerdo a las propiedades de Prophet es necesario convertir los datos de series de tiempo a dataframe teniendo presente que los datos se encuentran en meses. Prophet funciona mejor con series temporales que tienen una fuerte estacionalidad y varias temporadas de datos históricos.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="modelización.html#cb95-1" tabindex="-1"></a><span class="fu">library</span>(prophet)</span>
<span id="cb95-2"><a href="modelización.html#cb95-2" tabindex="-1"></a><span class="fu">library</span>(tseries)</span>
<span id="cb95-3"><a href="modelización.html#cb95-3" tabindex="-1"></a></span>
<span id="cb95-4"><a href="modelización.html#cb95-4" tabindex="-1"></a><span class="co"># Se convierte la serie de tiempo a un data.frame para Prophet</span></span>
<span id="cb95-5"><a href="modelización.html#cb95-5" tabindex="-1"></a></span>
<span id="cb95-6"><a href="modelización.html#cb95-6" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb95-7"><a href="modelización.html#cb95-7" tabindex="-1"></a>  <span class="at">ds =</span> <span class="fu">seq.Date</span>(<span class="at">from =</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-01-01&quot;</span>), <span class="at">by =</span> <span class="st">&quot;month&quot;</span>, <span class="at">length.out =</span> <span class="fu">length</span>(covid_ts_diff2)),</span>
<span id="cb95-8"><a href="modelización.html#cb95-8" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">as.numeric</span>(covid_ts_diff2)</span>
<span id="cb95-9"><a href="modelización.html#cb95-9" tabindex="-1"></a>)</span>
<span id="cb95-10"><a href="modelización.html#cb95-10" tabindex="-1"></a></span>
<span id="cb95-11"><a href="modelización.html#cb95-11" tabindex="-1"></a><span class="co"># Se visualizan los primeros registros para verificar</span></span>
<span id="cb95-12"><a href="modelización.html#cb95-12" tabindex="-1"></a></span>
<span id="cb95-13"><a href="modelización.html#cb95-13" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<pre><code>##           ds        y
## 1 2020-01-01  2171728
## 2 2020-02-01  3373889
## 3 2020-03-01 -1621454
## 4 2020-04-01 -1209542
## 5 2020-05-01  5568034
## 6 2020-06-01  4556391</code></pre>
<p>Una vez verificado el dataset, se ajusta el modelo Prophet:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="modelización.html#cb97-1" tabindex="-1"></a><span class="co"># Se crea y ajusta el modelo Prophet con estacionalidades semanal y diaria habilitadas</span></span>
<span id="cb97-2"><a href="modelización.html#cb97-2" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">prophet</span>(<span class="at">weekly.seasonality =</span> <span class="cn">TRUE</span>, <span class="at">daily.seasonality =</span> <span class="cn">TRUE</span>)</span>
<span id="cb97-3"><a href="modelización.html#cb97-3" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">fit.prophet</span>(m, df)</span></code></pre></div>
<p>Prophet por defecto ha deshabilitado la estacionalidad semanal y diaria para el modelo. Esto se debe a que Prophet detecta que la frecuencia de los datos es mensual, y por lo tanto, la estacionalidad semanal y diaria no es relevante en este contexto.</p>
<p>Se crea un dataframe para hacer las predicciones en el futuro con las fechas deseadas de meses.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="modelización.html#cb98-1" tabindex="-1"></a><span class="co"># Se Crea un data frame de fechas futuras para predicciones (24 meses en el futuro)</span></span>
<span id="cb98-2"><a href="modelización.html#cb98-2" tabindex="-1"></a>future <span class="ot">&lt;-</span> <span class="fu">make_future_dataframe</span>(m, <span class="at">periods =</span> <span class="dv">24</span>, <span class="at">freq =</span> <span class="st">&quot;month&quot;</span>)</span></code></pre></div>
<p>Se utiliza el modelo ajustado para hacer las predicciones sobre el conjunto de datos futuros</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="modelización.html#cb99-1" tabindex="-1"></a><span class="co">#  Predicciones:</span></span>
<span id="cb99-2"><a href="modelización.html#cb99-2" tabindex="-1"></a></span>
<span id="cb99-3"><a href="modelización.html#cb99-3" tabindex="-1"></a>forecast <span class="ot">&lt;-</span> <span class="fu">predict</span>(m, future)</span></code></pre></div>
<p>Finalmente se realiza la visualización de las predicciones con los datos ajustados:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="modelización.html#cb100-1" tabindex="-1"></a><span class="fu">plot</span>(m, forecast)</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>En la gráfica de la predicción se observan puntos negros que reflejan los datos históricos reales de la serie de datos que se han utilizado para ajustar el modelo. Con la línea azul se observan los valores predichos por el modelo y se extiende más allá de los datos históricos y genera una estimación de los posibles datos futuros. Se observa variabilidad en dicha predicción.</p>
<p>La zona sombreada corresponde a los intervalos de incertidumbre mostrando el rango en el que se espera que caigan los valores futuros con cierto nivel de confianza.</p>
<p>A continuación, se visualizan los componentes de las predicciones:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="modelización.html#cb101-1" tabindex="-1"></a><span class="fu">prophet_plot_components</span>(m, forecast)</span></code></pre></div>
<p><img src="SeriesTiempoCOVID_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<p>En las gráficas se puede observar claramente la tendencia real de los datos. Específicamente, se muestra que los casos de COVID-19 presentan una disminución en los próximos 24 meses. Este comportamiento también se refleja en los modelos presentados anteriormente, confirmando la consistencia de las predicciones.</p>
<p>La visualización de la tendencia descendente proporciona una perspectiva optimista sobre la evolución de la pandemia, respaldada por los análisis previos y los datos históricos diferenciados.</p>
<p>Podemos observar las fluctuaciones en los datos a lo largo de la semana y el día, lo que nos proporciona información detallada sobre la dinámica de los casos de COVID-19. Se destaca que los miércoles se registran el menor número de nuevos casos de COVID-19, mientras que los sábados muestran el pico más alto en el número de casos. Este patrón semanal revela posibles correlaciones con actividades humanas y comportamientos sociales.</p>
<p>Además, se identifica un notable aumento en el número de casos nuevos entre los meses de julio y abril, indicando un período de mayor transmisión de la enfermedad. Esta tendencia sugiere la importancia de implementar medidas preventivas y de control durante ese período para contener la propagación del virus.</p>
<p>Por último, se observa que el número de casos de COVID-19 es relativamente bajo entre las 10:00 p.m. y las 2:00 a.m. Esto puede estar relacionado con el cumplimiento de las medidas de distanciamiento social durante las horas nocturnas, así como con las actividades laborales y sociales que ocurren durante el día. No obstante, los datos no reflejan la hora exacta del contagio, sino la hora del reporte del caso positivo.</p>
<p>En resumen, la visualización de estos patrones temporales nos ofrece una perspectiva detallada sobre la distribución de los casos de Covid, lo que puede ser útil para informar y adaptar estrategias de prevención y control de la enfermedad.</p>
<p><strong>Nota sobre el proceso de los dataset:</strong></p>
<p>Se realizó una prueba transformando el set de datos a una escala logarítmica, la prueba de dicker fuller reflejaba no estacionariedad, por lo que se diferenció la serie logarítmica y al confirmar estacionariedad se corrió el modelo Prophet. Los resultados de Prophet fueron iguales a los del dataset sin transformación logarítmica, razón por la cual, se dejan los datos sin dicha transformación, solo con la segunda diferenciación que nos confirma estacionariedad.</p>
<p><strong>Justificación del Uso del Modelo Prophet como una Regresión en una Serie Temporal</strong></p>
<p>Prophet es un modelo que combina características de modelos de regresión y de series de tiempo. El modelo Prophet es adecuado para nuestros datos de casos de Covid-19 porque el número de casos nuevos sigue cambiando de forma no lineal, con algunos picos, algunas caídas y algunas mesetas. Esta técnica puede manejar estos patrones complicados mejor que una modelo lineal. Prophet también puede detectar y adaptarse a los cambios de tendencia dando pronósticos más precisos. Esta flexibilidad y capacidad de ajuste hacen que sea una herramienta sólida para analizar y predecir este tipo de series temporales.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="descomposición-de-la-serie-de-tiempo..html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
